import { SymbolInfo } from '../types/trading';

// Expanded 24 Major & Minor Forex FIAT Pairs
export const FOREX_SYMBOLS: SymbolInfo[] = [
  {
    symbol: 'EURUSD',
    name: 'EUR / USD',
    type: 'forex',
    tvSymbol: 'FX:EURUSD',
    basePrice: 1.0875,
    precision: 5,
    category: 'Forex Majors',
    description: 'Euro vs US Dollar - Most heavily traded global currency pair.',
    quoteCurrency: 'USD',
    pipSize: 0.0001,
    spreadPips: 0.8,
  },
  {
    symbol: 'GBPUSD',
    name: 'GBP / USD',
    type: 'forex',
    tvSymbol: 'FX:GBPUSD',
    basePrice: 1.2942,
    precision: 5,
    category: 'Forex Majors',
    description: 'British Pound vs US Dollar (Cable).',
    quoteCurrency: 'USD',
    pipSize: 0.0001,
    spreadPips: 1.2,
  },
  {
    symbol: 'USDJPY',
    name: 'USD / JPY',
    type: 'forex',
    tvSymbol: 'FX:USDJPY',
    basePrice: 156.45,
    precision: 3,
    category: 'Forex Majors',
    description: 'US Dollar vs Japanese Yen - Asian market anchor pair.',
    quoteCurrency: 'JPY',
    pipSize: 0.01,
    spreadPips: 0.9,
  },
  {
    symbol: 'AUDUSD',
    name: 'AUD / USD',
    type: 'forex',
    tvSymbol: 'FX:AUDUSD',
    basePrice: 0.6684,
    precision: 5,
    category: 'Forex Majors',
    description: 'Australian Dollar vs US Dollar (Aussie).',
    quoteCurrency: 'USD',
    pipSize: 0.0001,
    spreadPips: 1.1,
  },
  {
    symbol: 'USDCHF',
    name: 'USD / CHF',
    type: 'forex',
    tvSymbol: 'FX:USDCHF',
    basePrice: 0.8912,
    precision: 5,
    category: 'Forex Majors',
    description: 'US Dollar vs Swiss Franc (Swissy safe haven).',
    quoteCurrency: 'CHF',
    pipSize: 0.0001,
    spreadPips: 1.4,
  },
  {
    symbol: 'NZDUSD',
    name: 'NZD / USD',
    type: 'forex',
    tvSymbol: 'FX:NZDUSD',
    basePrice: 0.6120,
    precision: 5,
    category: 'Forex Majors',
    description: 'New Zealand Dollar vs US Dollar (Kiwi).',
    quoteCurrency: 'USD',
    pipSize: 0.0001,
    spreadPips: 1.5,
  },
  {
    symbol: 'USDCAD',
    name: 'USD / CAD',
    type: 'forex',
    tvSymbol: 'FX:USDCAD',
    basePrice: 1.3650,
    precision: 5,
    category: 'Forex Majors',
    description: 'US Dollar vs Canadian Dollar (Loonie commodity currency).',
    quoteCurrency: 'CAD',
    pipSize: 0.0001,
    spreadPips: 1.3,
  },
  {
    symbol: 'EURGBP',
    name: 'EUR / GBP',
    type: 'forex',
    tvSymbol: 'FX:EURGBP',
    basePrice: 0.8403,
    precision: 5,
    category: 'Forex Minors',
    description: 'Euro vs British Pound - Key European cross pair.',
    quoteCurrency: 'GBP',
    pipSize: 0.0001,
    spreadPips: 1.0,
  },
  {
    symbol: 'EURJPY',
    name: 'EUR / JPY',
    type: 'forex',
    tvSymbol: 'FX:EURJPY',
    basePrice: 170.15,
    precision: 3,
    category: 'Forex Minors',
    description: 'Euro vs Japanese Yen cross rate.',
    quoteCurrency: 'JPY',
    pipSize: 0.01,
    spreadPips: 1.2,
  },
  {
    symbol: 'GBPJPY',
    name: 'GBP / JPY',
    type: 'forex',
    tvSymbol: 'FX:GBPJPY',
    basePrice: 202.48,
    precision: 3,
    category: 'Forex Minors',
    description: 'British Pound vs Japanese Yen (The Dragon / Geppy).',
    quoteCurrency: 'JPY',
    pipSize: 0.01,
    spreadPips: 1.8,
  },
  {
    symbol: 'AUDJPY',
    name: 'AUD / JPY',
    type: 'forex',
    tvSymbol: 'FX:AUDJPY',
    basePrice: 104.58,
    precision: 3,
    category: 'Forex Minors',
    description: 'Australian Dollar vs Japanese Yen carry-trade pair.',
    quoteCurrency: 'JPY',
    pipSize: 0.01,
    spreadPips: 1.5,
  },
  {
    symbol: 'NZDJPY',
    name: 'NZD / JPY',
    type: 'forex',
    tvSymbol: 'FX:NZDJPY',
    basePrice: 95.74,
    precision: 3,
    category: 'Forex Minors',
    description: 'New Zealand Dollar vs Japanese Yen.',
    quoteCurrency: 'JPY',
    pipSize: 0.01,
    spreadPips: 1.6,
  },
  {
    symbol: 'CADJPY',
    name: 'CAD / JPY',
    type: 'forex',
    tvSymbol: 'FX:CADJPY',
    basePrice: 114.61,
    precision: 3,
    category: 'Forex Minors',
    description: 'Canadian Dollar vs Japanese Yen.',
    quoteCurrency: 'JPY',
    pipSize: 0.01,
    spreadPips: 1.7,
  },
  {
    symbol: 'CHFJPY',
    name: 'CHF / JPY',
    type: 'forex',
    tvSymbol: 'FX:CHFJPY',
    basePrice: 175.54,
    precision: 3,
    category: 'Forex Minors',
    description: 'Swiss Franc vs Japanese Yen.',
    quoteCurrency: 'JPY',
    pipSize: 0.01,
    spreadPips: 1.9,
  },
  {
    symbol: 'EURAUD',
    name: 'EUR / AUD',
    type: 'forex',
    tvSymbol: 'FX:EURAUD',
    basePrice: 1.6270,
    precision: 5,
    category: 'Forex Minors',
    description: 'Euro vs Australian Dollar.',
    quoteCurrency: 'AUD',
    pipSize: 0.0001,
    spreadPips: 1.8,
  },
  {
    symbol: 'EURCAD',
    name: 'EUR / CAD',
    type: 'forex',
    tvSymbol: 'FX:EURCAD',
    basePrice: 1.4844,
    precision: 5,
    category: 'Forex Minors',
    description: 'Euro vs Canadian Dollar.',
    quoteCurrency: 'CAD',
    pipSize: 0.0001,
    spreadPips: 1.6,
  },
  {
    symbol: 'EURNZD',
    name: 'EUR / NZD',
    type: 'forex',
    tvSymbol: 'FX:EURNZD',
    basePrice: 1.7769,
    precision: 5,
    category: 'Forex Minors',
    description: 'Euro vs New Zealand Dollar.',
    quoteCurrency: 'NZD',
    pipSize: 0.0001,
    spreadPips: 2.1,
  },
  {
    symbol: 'GBPAUD',
    name: 'GBP / AUD',
    type: 'forex',
    tvSymbol: 'FX:GBPAUD',
    basePrice: 1.9362,
    precision: 5,
    category: 'Forex Minors',
    description: 'British Pound vs Australian Dollar.',
    quoteCurrency: 'AUD',
    pipSize: 0.0001,
    spreadPips: 2.0,
  },
  {
    symbol: 'GBPCAD',
    name: 'GBP / CAD',
    type: 'forex',
    tvSymbol: 'FX:GBPCAD',
    basePrice: 1.7665,
    precision: 5,
    category: 'Forex Minors',
    description: 'British Pound vs Canadian Dollar.',
    quoteCurrency: 'CAD',
    pipSize: 0.0001,
    spreadPips: 1.9,
  },
  {
    symbol: 'GBPNZD',
    name: 'GBP / NZD',
    type: 'forex',
    tvSymbol: 'FX:GBPNZD',
    basePrice: 2.1147,
    precision: 5,
    category: 'Forex Minors',
    description: 'British Pound vs New Zealand Dollar.',
    quoteCurrency: 'NZD',
    pipSize: 0.0001,
    spreadPips: 2.4,
  },
  {
    symbol: 'AUDCAD',
    name: 'AUD / CAD',
    type: 'forex',
    tvSymbol: 'FX:AUDCAD',
    basePrice: 0.9124,
    precision: 5,
    category: 'Forex Minors',
    description: 'Australian Dollar vs Canadian Dollar.',
    quoteCurrency: 'CAD',
    pipSize: 0.0001,
    spreadPips: 1.5,
  },
  {
    symbol: 'AUDNZD',
    name: 'AUD / NZD',
    type: 'forex',
    tvSymbol: 'FX:AUDNZD',
    basePrice: 1.0921,
    precision: 5,
    category: 'Forex Minors',
    description: 'Australian Dollar vs New Zealand Dollar.',
    quoteCurrency: 'NZD',
    pipSize: 0.0001,
    spreadPips: 1.7,
  },
  {
    symbol: 'USDSGD',
    name: 'USD / SGD',
    type: 'forex',
    tvSymbol: 'FX:USDSGD',
    basePrice: 1.3460,
    precision: 5,
    category: 'Forex Exotic',
    description: 'US Dollar vs Singapore Dollar.',
    quoteCurrency: 'SGD',
    pipSize: 0.0001,
    spreadPips: 1.4,
  },
  {
    symbol: 'USDIDR',
    name: 'USD / IDR',
    type: 'forex',
    tvSymbol: 'FX_IDC:USDIDR',
    basePrice: 16200.0,
    precision: 0,
    category: 'Forex Exotic',
    description: 'US Dollar vs Indonesian Rupiah.',
    quoteCurrency: 'IDR',
    pipSize: 1.0,
    spreadPips: 15.0,
  },
];

// Top Cryptocurrencies Database Catalog
export const CRYPTO_SYMBOLS: SymbolInfo[] = [
  { symbol: 'BTCUSDT', name: 'Bitcoin', type: 'crypto', tvSymbol: 'BINANCE:BTCUSDT', basePrice: 65420.50, precision: 2, category: 'Layer 1', description: 'Primary digital asset & store of value.', quoteCurrency: 'USDT' },
  { symbol: 'ETHUSDT', name: 'Ethereum', type: 'crypto', tvSymbol: 'BINANCE:ETHUSDT', basePrice: 3480.20, precision: 2, category: 'Layer 1', description: 'Smart contract platform powering DeFi.', quoteCurrency: 'USDT' },
  { symbol: 'SOLUSDT', name: 'Solana', type: 'crypto', tvSymbol: 'BINANCE:SOLUSDT', basePrice: 145.80, precision: 2, category: 'Layer 1', description: 'High-speed layer-1 blockchain.', quoteCurrency: 'USDT' },
  { symbol: 'BNBUSDT', name: 'BNB', type: 'crypto', tvSymbol: 'BINANCE:BNBUSDT', basePrice: 580.40, precision: 2, category: 'Exchange', description: 'Native utility token for BNB Chain.', quoteCurrency: 'USDT' },
  { symbol: 'XRPUSDT', name: 'XRP', type: 'crypto', tvSymbol: 'BINANCE:XRPUSDT', basePrice: 0.5840, precision: 4, category: 'Payments', description: 'Cross-border liquidity settlement network.', quoteCurrency: 'USDT' },
  { symbol: 'ADAUSDT', name: 'Cardano', type: 'crypto', tvSymbol: 'BINANCE:ADAUSDT', basePrice: 0.3820, precision: 4, category: 'Layer 1', description: 'Proof-of-stake academic blockchain.', quoteCurrency: 'USDT' },
  { symbol: 'DOGEUSDT', name: 'Dogecoin', type: 'crypto', tvSymbol: 'BINANCE:DOGEUSDT', basePrice: 0.1240, precision: 4, category: 'Meme', description: 'Decentralized peer-to-peer meme currency.', quoteCurrency: 'USDT' },
  { symbol: 'AVAXUSDT', name: 'Avalanche', type: 'crypto', tvSymbol: 'BINANCE:AVAXUSDT', basePrice: 28.40, precision: 2, category: 'Layer 1', description: 'High-throughput subnetwork platform.', quoteCurrency: 'USDT' },
  { symbol: 'LINKUSDT', name: 'Chainlink', type: 'crypto', tvSymbol: 'BINANCE:LINKUSDT', basePrice: 14.20, precision: 2, category: 'Oracle', description: 'Decentralized oracle network connecting smart contracts.', quoteCurrency: 'USDT' },
  { symbol: 'DOTUSDT', name: 'Polkadot', type: 'crypto', tvSymbol: 'BINANCE:DOTUSDT', basePrice: 6.35, precision: 2, category: 'Interoperability', description: 'Multi-chain sharded interoperable network.', quoteCurrency: 'USDT' },
  { symbol: 'NEARUSDT', name: 'NEAR Protocol', type: 'crypto', tvSymbol: 'BINANCE:NEARUSDT', basePrice: 5.15, precision: 3, category: 'Layer 1', description: 'User-friendly sharded cloud platform.', quoteCurrency: 'USDT' },
  { symbol: 'SUIUSDT', name: 'Sui', type: 'crypto', tvSymbol: 'BINANCE:SUIUSDT', basePrice: 1.85, precision: 4, category: 'Layer 1', description: 'Object-centric Move programming blockchain.', quoteCurrency: 'USDT' },
  { symbol: 'MATICUSDT', name: 'Polygon', type: 'crypto', tvSymbol: 'BINANCE:MATICUSDT', basePrice: 0.5210, precision: 4, category: 'Layer 2', description: 'Ethereum scaling subnetwork ecosystem.', quoteCurrency: 'USDT' },
  { symbol: 'PEPEUSDT', name: 'Pepe', type: 'crypto', tvSymbol: 'BINANCE:PEPEUSDT', basePrice: 0.0000095, precision: 7, category: 'Meme', description: 'Popular deflationary meme token.', quoteCurrency: 'USDT' },
  { symbol: 'SHIBUSDT', name: 'Shiba Inu', type: 'crypto', tvSymbol: 'BINANCE:SHIBUSDT', basePrice: 0.0000178, precision: 7, category: 'Meme', description: 'Decentralized community building ecosystem.', quoteCurrency: 'USDT' },
  { symbol: 'TRXUSDT', name: 'TRON', type: 'crypto', tvSymbol: 'BINANCE:TRXUSDT', basePrice: 0.1340, precision: 4, category: 'Layer 1', description: 'High-speed content distribution platform.', quoteCurrency: 'USDT' },
  { symbol: 'LTCUSDT', name: 'Litecoin', type: 'crypto', tvSymbol: 'BINANCE:LTCUSDT', basePrice: 72.80, precision: 2, category: 'Payments', description: 'Lightweight silver to Bitcoin gold.', quoteCurrency: 'USDT' },
  { symbol: 'BCHUSDT', name: 'Bitcoin Cash', type: 'crypto', tvSymbol: 'BINANCE:BCHUSDT', basePrice: 345.50, precision: 2, category: 'Payments', description: 'Peer-to-peer electronic cash system.', quoteCurrency: 'USDT' },
  { symbol: 'UNIUSDT', name: 'Uniswap', type: 'crypto', tvSymbol: 'BINANCE:UNIUSDT', basePrice: 7.60, precision: 2, category: 'DeFi', description: 'Automated liquidity protocol governance token.', quoteCurrency: 'USDT' },
  { symbol: 'APTUSDT', name: 'Aptos', type: 'crypto', tvSymbol: 'BINANCE:APTUSDT', basePrice: 8.90, precision: 2, category: 'Layer 1', description: 'Move language high-safety blockchain.', quoteCurrency: 'USDT' },
  { symbol: 'FETUSDT', name: 'Artificial Superintelligence Alliance', type: 'crypto', tvSymbol: 'BINANCE:FETUSDT', basePrice: 1.42, precision: 3, category: 'AI', description: 'Decentralized artificial intelligence ecosystem.', quoteCurrency: 'USDT' },
  { symbol: 'RENDERUSDT', name: 'Render Token', type: 'crypto', tvSymbol: 'BINANCE:RENDERUSDT', basePrice: 5.85, precision: 2, category: 'AI & GPU', description: 'Distributed GPU rendering network.', quoteCurrency: 'USDT' },
  { symbol: 'ATOMUSDT', name: 'Cosmos', type: 'crypto', tvSymbol: 'BINANCE:ATOMUSDT', basePrice: 4.90, precision: 2, category: 'Interoperability', description: 'Internet of Blockchains framework.', quoteCurrency: 'USDT' },
  { symbol: 'XLMUSDT', name: 'Stellar', type: 'crypto', tvSymbol: 'BINANCE:XLMUSDT', basePrice: 0.0980, precision: 4, category: 'Payments', description: 'Open network for financial transfers.', quoteCurrency: 'USDT' }
];

export const SUPPORTED_SYMBOLS: SymbolInfo[] = [...CRYPTO_SYMBOLS, ...FOREX_SYMBOLS];

export const getSymbolDetails = (symbol: string): SymbolInfo => {
  return (
    SUPPORTED_SYMBOLS.find((s) => s.symbol === symbol) || SUPPORTED_SYMBOLS[0]
  );
};
